@echo off
echo Dang tim va tat cong 8080...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :8080') do taskkill /F /PID %%a >nul 2>&1
echo Dang xoa cache thu muc target...
rmdir /s /q target
echo Dang khoi dong lai Spring Boot...
call mvnw.cmd clean spring-boot:run
